[package]
name = "bc-shamir"
version = "0.6.0"
edition = "2021"
description = "Shamir's Secret Sharing (SSS) for Rust."
authors = ["Blockchain Commons"]
repository = "https://github.com/BlockchainCommons/bc-shamir-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
documentation = "https://docs.rs/bc-shamir"
keywords = ["cryptography"]                                        # Up to five
categories = ["cryptography"]                                      # https://crates.io/category_slugs

[dependencies]
bc-rand = "^0.3.0"
bc-crypto = "^0.7.0"

thiserror = "^1.0.48"

[dev-dependencies]
hex-literal = "^0.4.1"
hex = "^0.4.3"
version-sync = "^0.9.0"
rand = "^0.8.5"
