[package]
name = "bc-shamir"
version = "0.1.0"
edition = "2021"
description = "Shamir's Secret Sharing (SSS) for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-shamir-rust"
readme = "README.md"
categories = ["cryptography"]
documentation = "https://docs.rs/bc-shamir"

[dependencies]
bc-crypto = "0.1.0"

[dev-dependencies]
hex-literal = "0.4.1"
hex = "0.4.3"
version-sync = "0.9"
